[package]
name = "substrate-forum-module"
version = "1.0.0"
authors = ["Bedeho Mender <bedeho.mender@protonmail.com>"]
edition = "2018"

[dependencies]
# restrict version of syn, see https://github.com/paritytech/substrate/issues/2326
syn = { version = ">= 0.15.26, <= 0.15.44", features = ["full"] }
hex-literal = "0.1.0"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
parity-codec = { version = "3.2", default-features = false }
parity-codec-derive = { version = "3.1", default-features = false }
rstd = { package = 'sr-std', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
runtime-primitives = { package = 'sr-primitives', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
srml-support = { package = 'srml-support', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
srml-support-procedural = { package = 'srml-support-procedural', git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
system = { package = 'srml-system', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
balances = { package = 'srml-balances', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
branch = 'v1.0'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
branch = 'v1.0'

[dev-dependencies]
runtime-io = { package = 'sr-io', default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}
primitives = { package = 'substrate-primitives', git = "https://github.com/paritytech/substrate.git", branch = 'v1.0'}

[features]
default = ["std"]
std = [
	"serde",
	"serde_derive",
	"parity-codec/std",
	"parity-codec-derive/std",
	"rstd/std",
	"runtime-io/std",
	"runtime-primitives/std",
	"srml-support/std",
	"system/std",
  	"balances/std",
	"timestamp/std",
]
